"""add template key/version and contract template_id/answers_json

Revision ID: c8e5729f792b
Revises: 14a6f27ed9d0
Create Date: 2026-06-16 19:22:10.769061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8e5729f792b'
down_revision: Union[str, None] = '14a6f27ed9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('template_id', sa.UUID(), nullable=True))
    op.add_column('contracts', sa.Column('answers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'contracts', 'templates', ['template_id'], ['id'])
    op.add_column('templates', sa.Column('key', sa.String(), nullable=False))
    op.add_column('templates', sa.Column('version', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_templates_key'), 'templates', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_templates_key'), table_name='templates')
    op.drop_column('templates', 'version')
    op.drop_column('templates', 'key')
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'answers_json')
    op.drop_column('contracts', 'template_id')
    # ### end Alembic commands ###
