-- =============================================================================
-- schema.sql — AI layer database schema
--
-- PostgreSQL schema for the two tables directly produced by the AI layer
-- (ai-layer/). Designed for PostgreSQL 13+ with the pgvector extension
-- available (pgvector is not used by these tables directly, but is part of
-- the overall architecture plan for future similarity-search features).
--
-- This file defines schema only — no connection code, no ORM mappings.
--
-- To create these tables:
--   psql -d <your_database> -f schema.sql
--
-- Prerequisites:
--   PostgreSQL 13+ — gen_random_uuid() is built in from PG 13.
--   On PG 12 or earlier, uncomment the line below:
--     CREATE EXTENSION IF NOT EXISTS pgcrypto;
-- =============================================================================


-- =============================================================================
-- TABLE: contract_terms
--
-- Stores the structured output of extract_terms() from extraction.py.
-- Each row is one extraction run on one contract.
--
-- WHAT IS NOT STORED HERE:
--   The raw contract text. Contracts are confidential documents and must not
--   sit in a plaintext column. This table stores only the structured terms
--   that the AI extracted — the output — not the source document itself.
--   Store the actual contract in a separate contracts table with encryption
--   at rest and appropriate access controls.
--
-- Columns mirror the return value of extract_terms():
--   result['terms'][field]['extracted']        → the field column
--   result['terms'][field]['confidence']       → <field>_confidence
--   field in result['low_confidence_fields']   → <field>_low_confidence
-- =============================================================================

CREATE TABLE contract_terms (

    -- UUID primary key, generated by the database.
    -- UUIDs are used throughout (rather than serial integers) because they are
    -- safe to expose in URLs and APIs without leaking row counts or allowing
    -- sequential enumeration of records.
    id                              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

    -- The contract this extraction belongs to.
    -- This is a placeholder for a future foreign key to the contracts table,
    -- which does not exist yet. When that table is created, add the constraint:
    --
    --   ALTER TABLE contract_terms
    --     ADD CONSTRAINT fk_contract
    --     FOREIGN KEY (contract_id) REFERENCES contracts(id);
    --
    -- Until then, the application layer must supply a stable UUID per contract.
    contract_id                     UUID        NOT NULL,

    -- ── Extracted fields ─────────────────────────────────────────────────────
    --
    -- Each field is nullable: if the model could not find the term in the
    -- contract, extract_terms() returns null for 'extracted', stored as NULL.
    --
    -- Every field is paired with:
    --   <field>_confidence      REAL   model's confidence score (0.0–1.0).
    --                                  NULL only if the extracted value is NULL
    --                                  and no score was returned (edge case).
    --   <field>_low_confidence  BOOL   TRUE if confidence was below the
    --                                  LOW_CONFIDENCE_THRESHOLD at extraction
    --                                  time (threshold = 0.7 in extraction.py).
    --
    -- Why one boolean per field rather than a single low_confidence_fields
    -- array column?
    --   A boolean per field makes queries direct and indexable without array
    --   operators or JSON parsing:
    --     SELECT * FROM contract_terms WHERE effective_date_low_confidence = TRUE;
    --   If EXTRACTION_SCHEMA in extraction.py gains new fields in future,
    --   add matching column groups here.

    -- parties: all named parties to the contract.
    -- extract_terms() returns this as a Python list (e.g. ["Acme Ltd", "Globex Inc"]).
    -- Stored as TEXT[] (PostgreSQL native string array) — no JSON needed for a
    -- flat list of strings, and array operators (e.g. @>) work out of the box.
    parties                         TEXT[],
    parties_confidence              REAL        CHECK (parties_confidence BETWEEN 0.0 AND 1.0),
    parties_low_confidence          BOOLEAN     NOT NULL DEFAULT FALSE,

    -- effective_date: the date the contract takes effect.
    -- Stored as TEXT, not DATE, because extract_terms() is instructed to copy
    -- the date string exactly as it appears in the document. Legal dates often
    -- use non-standard formats ("the 1st day of January, 2024") that would be
    -- lost or ambiguous if parsed to a typed DATE column.
    effective_date                  TEXT,
    effective_date_confidence       REAL        CHECK (effective_date_confidence BETWEEN 0.0 AND 1.0),
    effective_date_low_confidence   BOOLEAN     NOT NULL DEFAULT FALSE,

    -- contract_value: monetary value or payment terms as extracted text.
    -- Named contract_value (not value) to match the field key in extraction.py's
    -- EXTRACTION_SCHEMA and to avoid collision with the SQL reserved word VALUE.
    contract_value                  TEXT,
    contract_value_confidence       REAL        CHECK (contract_value_confidence BETWEEN 0.0 AND 1.0),
    contract_value_low_confidence   BOOLEAN     NOT NULL DEFAULT FALSE,

    -- renewal_terms: how and when the contract renews.
    renewal_terms                   TEXT,
    renewal_terms_confidence        REAL        CHECK (renewal_terms_confidence BETWEEN 0.0 AND 1.0),
    renewal_terms_low_confidence    BOOLEAN     NOT NULL DEFAULT FALSE,

    -- termination_terms: conditions under which either party may end the contract.
    termination_terms               TEXT,
    termination_terms_confidence    REAL        CHECK (termination_terms_confidence BETWEEN 0.0 AND 1.0),
    termination_terms_low_confidence BOOLEAN    NOT NULL DEFAULT FALSE,

    -- notice_period: required advance notice period (e.g. "30 days", "3 months").
    notice_period                   TEXT,
    notice_period_confidence        REAL        CHECK (notice_period_confidence BETWEEN 0.0 AND 1.0),
    notice_period_low_confidence    BOOLEAN     NOT NULL DEFAULT FALSE,

    -- ── Metadata ─────────────────────────────────────────────────────────────

    -- TIMESTAMPTZ (timestamp with time zone) rather than TIMESTAMP so that the
    -- stored value is unambiguous regardless of the server's local timezone.
    created_at                      TIMESTAMPTZ NOT NULL DEFAULT NOW()

);

-- Look up all extractions for a given contract.
CREATE INDEX idx_contract_terms_contract_id
    ON contract_terms (contract_id);

-- Quickly find all rows where any field was flagged low-confidence — useful
-- for a review queue that surfaces uncertain extractions for human checking.
CREATE INDEX idx_contract_terms_any_low_confidence
    ON contract_terms (contract_id)
    WHERE parties_low_confidence
       OR effective_date_low_confidence
       OR contract_value_low_confidence
       OR renewal_terms_low_confidence
       OR termination_terms_low_confidence
       OR notice_period_low_confidence;


-- =============================================================================
-- TABLE: ai_events
--
-- Audit log of every guardrail routing decision from run_guardrail() in
-- guardrail_classifier.py. One row per query, regardless of outcome.
--
-- WHAT IS NOT STORED HERE:
--   The raw query text. Queries often contain sensitive details about the
--   user's legal situation. Logging only the routing decision (outcome,
--   classification, confidence, reason) provides a meaningful audit trail
--   without retaining the confidential content of what was asked.
--   This matches the logging approach already used in the Python code:
--   internal loggers record decision metadata, never the query itself.
--
-- run_guardrail() operates in two layers:
--   Layer 1 — denylist (guardrail.py): pure pattern-matching, no API call.
--             Catches obviously advice-seeking queries (e.g. "should I sign?").
--             When this layer fires: classification = NULL, reason = 'denylist_match'.
--   Layer 2 — LLM classifier (guardrail_classifier.py): called only if Layer 1
--             found no match. Classifies the query and sets classification to
--             one of the allowed text values below.
-- =============================================================================

CREATE TABLE ai_events (

    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

    -- The user who submitted the query.
    -- Every guardrail event must be linked to a user so the audit trail is
    -- attributable. Populate this from the authenticated session before
    -- inserting the row — never NULL in production.
    --
    -- Placeholder for a future foreign key to the users table:
    --   ALTER TABLE ai_events
    --     ADD CONSTRAINT fk_user
    --     FOREIGN KEY (user_id) REFERENCES users(id);
    user_id             UUID        NOT NULL,

    -- TRUE  → query was routed to a human lawyer; AI did not answer.
    -- FALSE → query was cleared for the AI to handle.
    -- Never NULL: every guardrail call produces a definitive yes/no outcome.
    routed_to_human     BOOLEAN     NOT NULL,

    -- The LLM's classification label, or NULL when no LLM was called.
    --
    -- Possible values:
    --   NULL              Layer 1 (denylist) matched — no LLM was invoked, so
    --                     there is no classification label. Identify these rows
    --                     by reason = 'denylist_match', or by joining on
    --                     confidence IS NULL.
    --                     Also NULL if the LLM call failed or returned an
    --                     unreadable response (conservative default in effect).
    --   'informational'   LLM classified as a general question. routed_to_human
    --                     may still be TRUE if confidence was below the threshold
    --                     (CONFIDENCE_THRESHOLD = 0.75 in guardrail_classifier.py).
    --   'specific_advice' LLM classified as personal/situational advice.
    --                     Always routed_to_human = TRUE.
    --   'denylist_match'  Reserved for future use. The current Python code sets
    --                     classification = NULL for denylist matches and puts
    --                     'denylist_match' in the reason column. This value is
    --                     included in the CHECK so the application layer can
    --                     optionally write it explicitly if that is cleaner for
    --                     downstream queries.
    --
    -- The CHECK is written with an explicit IS NULL branch because the intent
    -- (NULL is a valid, meaningful state) should be obvious to a reader.
    classification      TEXT        CHECK (
                                        classification IS NULL
                                        OR classification IN (
                                            'informational',
                                            'specific_advice',
                                            'denylist_match'
                                        )
                                    ),

    -- LLM's self-reported confidence in its classification (0.0–1.0).
    -- NULL when Layer 1 (denylist) made the decision — no LLM confidence exists.
    -- Also NULL if the LLM call failed or the response could not be parsed.
    -- Constrained with explicit IS NULL branch for the same readability reason
    -- as the classification CHECK above.
    confidence          REAL        CHECK (
                                        confidence IS NULL
                                        OR confidence BETWEEN 0.0 AND 1.0
                                    ),

    -- The reason string returned by run_guardrail(). Always populated.
    --   'denylist_match'                → Layer 1 matched a denylist pattern.
    --   Model's one-sentence explanation→ Layer 2 classified the query.
    --   System note (e.g. "Low confidence (0.68 < 0.75); conservative default
    --   applied. Model reason: ...")    → Layer 2 applied the conservative default.
    reason              TEXT        NOT NULL,

    -- The LLM model identifier used for Layer 2 decisions.
    -- NULL when Layer 1 made the decision (no model was called).
    -- Populated from the MODEL constant in guardrail_classifier.py
    -- (currently 'llama-3.3-70b-versatile'). Stored so that future audits can
    -- identify decisions made by each model version, especially if the model is
    -- swapped or upgraded.
    model_used          TEXT,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()

);

-- Look up all guardrail events for a specific user.
CREATE INDEX idx_ai_events_user_id
    ON ai_events (user_id);

-- Filter or count by routing outcome — e.g. "how many queries were routed
-- to humans this week?" Partial indexes are more efficient than full-column
-- indexes when one value (TRUE) is the exception rather than the rule.
CREATE INDEX idx_ai_events_routed_to_human
    ON ai_events (routed_to_human);

-- Support time-range queries on the audit log.
CREATE INDEX idx_ai_events_created_at
    ON ai_events (created_at);
